### ISSUE TITLE
Gag App- CANCELLATION

### ISSUE THREAD

**Issue by mprincic** [wreiske/Rocket.Chat.App-Gag#1]
I would like to confirm that our trial has been cancelled.

**Comment by wreiske** [comment]
@mprincic hello! I have nothing to do with the subscriptions or trials. Please contact Rocket.Chat for that! Thank you.

**Comment by wreiske** [comment]
@mprincic I checked with the Rocket.Chat marketplace team and they assured me that the trials cancel when they end. 👍

**Comment by mprincic** [comment]
thanks so much! I appreciate it. We also have our rocket.chat contact confirming the cancellation
